#!/bin/bash



echo Was möchtest du tun?
echo "1.)Apache neustarten"
echo "2.)Seite deaktiveren"
echo "3.)Seite aktiveren"
echo "4.)Seite wechseln"
echo "5.)Rebooten"
read eingabe

if [ $eingabe == 1 ]
then
	sudo systemctl restart apache2;
	clear;
	echo Apache erfolgreich neugestartet

elif [ $eingabe == 2 ]
then
	read conf;
	sudo a2dissite $conf;
	sudo systemctl restart apache2;
	clear;
	echo Site wurde erfolgreich deaktiviert

elif [ $eingabe == 3 ]
then
	echo "Welche Seite aktiveren"
	read siteToActivate;
	sudo a2ensite $siteToActivate;
	sudo systemctl restart apache2;
	clear;
	echo Site wurde erfolgreich aktiviert

elif [ $eingabe == 4 ]
then
	echo "Welche Seite deaktivieren?"
	read siteChangeDeactivate;
	sudo a2dissite $siteChangeDeactivate;
	echo "Welche Seite aktivieren?"
	read siteChangeActivate;
	sudo a2ensite $siteChangeActivate;
	sudo systemctl restart apache2;
	clear;
	echo Seitenwechsel erfolgreich
elif [ $eingabe == 5 ]
then
	echo "Sicher neustarten?(Press enter...)"
	sudo reboot;
fi

